### ISSUE TITLE
MACRO

### ISSUE THREAD

**Issue by Mark-Jung** [nuvention-web/I-Back-2018#1]
Need CLEAN macro script to update the initial db from a google sheet.

**Comment by myidsan** [comment]
Need specification on what kind of db (sqlite, MySQL?), and file destination

**Comment by Mark-Jung** [comment]
sqlite. It's the data.db file at the home directory.

**Comment by Mark-Jung** [comment]
but why do you need it?

**Comment by Mark-Jung** [comment]
No longer needed.
